name: Installation

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: installation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: sh scripts/check-install.sh
